name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Project ID'
        required: true
      location:
        description: 'Location'
        required: true
      github_repository:
        description: 'GitHub repository'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login gcp
        run: |
          gcloud auth application-default login --no-launch-browser

      - name: Update JSON File
        run: |
          # Read the file content
          file_content=$(cat oidc-simple/application_default_credentials.json)

          # Update the values using sed
          updated_content=$(echo "$file_content" | \
                            sed -e "s/\"project_id\": \"CLIENT_ID\"/\"client_id\": \"${{ vars.CLIENT_ID }}\"/" \
                                -e "s/\"location\": \"CLIENT_SECRET\"/\"client_secret\": \"${{ vars.CLIENT_SECRET }}\"/")

          # Save the updated content back to the file
          echo "$updated_content" > oidc-simple/application_default_credentials.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib

      - name: Execute Python script
        run: |
          python authlogin.py ${{ github.event.inputs.project_id }} ${{ github.event.inputs.location }} ${{ github.event.inputs.github_repository }}
