name: Terraform Workflow

on:
  workflow_dispatch:
    inputs:
      project_id:
        description: 'Project ID'
        required: true
      github_repository:
        description: 'GitHub repository'
        required: true
      credentials:
        description: 'credentials'
        required: true
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Save state
        id: set_parameter
        run: | 
          echo "::save-state name=SECRET_CREDENTIAL::${{ github.event.inputs.credentials }}"
          echo "Parameter value has been set and masked."

      - name: JSON File Creation
        run: |
          sed -i "s|credentials|${{ steps.set_parameter.outputs.SECRET_CREDENTIAL }}|g" oidc-simple/application_default_credentials.json
          sed -i 's|"{|{|g' oidc-simple/application_default_credentials.json
          sed -i 's|}"|}|g' oidc-simple/application_default_credentials.json

      - name: read JSON File
        run: |
          # Read the file content
          cat oidc-simple/application_default_credentials.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-auth google-auth-oauthlib

      - name: Execute Python script
        run: |
          python authlogin.py ${{ github.event.inputs.project_id }} ${{ github.event.inputs.github_repository }}
